name: go_shopping
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.3
  cookie_jar: ^4.0.8
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.2.1
  onesignal_flutter: ^5.0.4
  firebase_core: ^2.25.5
  image_picker: ^0.8.7+4
  http_parser: ^4.0.0
  intl: ^0.19.0
  fl_chart: ^0.65.0
  month_year_picker: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "images/app_icon.png"  # Đường dẫn đến file icon
